[package]
name = "ssi-vc-test"
version = "0.1.0"
authors = ["Charles E. Lehner <charles.lehner@spruceid.com>"]
edition = "2018"

[dependencies]
ssi = { path = "../" }
serde_json = "1.0"
base64 = "0.12"
